name: No Free usage issue checker  # Actionåå­—ã€‚å¯ä»¥è‡ªå®šä¹‰

on:
  issues:
    types: [ opened, reopened ]  # åœ¨issueæ‰“å¼€å’Œé‡æ–°æ‰“å¼€æ—¶è°ƒç”¨

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check issue actor  # æ­¥éª¤åå­—ã€‚å¯ä»¥è‡ªå®šä¹‰ã€‚
        uses: fluttercandies/no-free-usage-action@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ç”±GitHubæä¾›çš„ä¸´æ—¶Tokenï¼Œå¿…é¡»åœ¨æ­¤å¤„è¿›è¡Œä¼ é€’ï¼Œä¸”å¿…é¡»ä¸ºè¿™ä¸ªå€¼ã€‚
          forked: '--no-forked'
          words: To support our project, please file the issue after you starred the repo. Thanks! ğŸ™‚
